name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations for your first issue for the _shriveling_world_ project, welcome onboard :) '
        pr-message: 'Congratulations for your first Pull Request for the _shriveling_world_ project'
